### ISSUE TITLE
1章（1.2以降）の誤記

### ISSUE THREAD

**Issue by niszet** [uribo/tokupon_ds#12]
1.2章は特にみつからなかったです。

https://github.com/uribo/tokupon_ds/blob/05118084c00f22c9a30fb312ba16b5ba69f2b31f/intro.qmd#L314

1.3の文章は書きかけですかね？ぶつ切りになっているので（修正予定だったらすみません）

----

以下は気になったけど修正するべきかは？な点です。

https://github.com/uribo/tokupon_ds/blob/05118084c00f22c9a30fb312ba16b5ba69f2b31f/intro.qmd#L344

参考文献ですが、書籍については`()`で囲われていますが、これは意図的でしょうか？デフォルトの表示がこの形ですかね？

あと、1章の演習問題の解答を見ていて、

https://github.com/uribo/tokupon_ds/blob/05118084c00f22c9a30fb312ba16b5ba69f2b31f/exercise.qmd#L14-L19

のコードが表示がないので、

https://github.com/uribo/tokupon_ds/blob/05118084c00f22c9a30fb312ba16b5ba69f2b31f/exercise.qmd#L36

のxがどこから出てきたんだろう？となりそうと思いました（最初見たとき、どう作っているのだろう？と私も思いました…）
問題の解説的にはデータの作り方自体はあまり重要ではないので、コード自体は載せなくても良いかもですが（考えすぎですかね…）

**Comment by uribo** [comment]
@niszet ありがとうございます。
1.3については書きかけです。ご迷惑おかけします。
また演習問題のxの出所が不明という点について、 https://github.com/uribo/tokupon_ds/commit/a7da6cbd40bab1dbed9cd14cf4ece79f4baf9094 で40人のテスト点数となるオブジェクトを生成するコードを追加しました。

参考文献の表記については #13 で改善したつもりでいます。括弧書きになっていたものも`著者名 (出版年)`の形式に変更しています。

**Comment by niszet** [comment]
@uribo ありがとうございます！確認しました。どちらも分かりやすくなったと思います！

**Comment by uribo** [comment]
一旦こちらはcloseさせていただきます。
